### ISSUE TITLE
适配请求：com.eg.android.AlipayGphone

### ISSUE THREAD

**Issue by Adlyq** [AutoAccountingOrg/AutoRule#311]
```
[{"mk":240962181343200020,"st":1,"isSc":0,"appId":"","mct":1727000024000,"pl":"{\"templateType\":\"BN\",\"commandType\":\"UPDATE\",\"withPushNfc\":\"Y\",\"expireLink\":\"\",\"msgType\":\"TODO\",\"icon\":\"https://gw.alipayobjects.com/mdn/rms_f96971/afts/img/A*leNcS41oUu0AAAAAAAAAAABkARQnAQ\",\"link\":\"alipays://platformapi/startapp?appId\u003d20000003\u0026actionType\u003dtoBillDetails\u0026tradeNO\u003d2024092222001436291419263036\u0026bizType\u003dTRADE?tagid\u003dMB_SEND_PH\",\"businessId\":\"PAY_HELPER_CARD_2088822946736298\",\"msgId\":\"27f152a04e783f5e923911dcff538ce800629\",\"templateCode\":\"00059_00094_zfzs001\",\"templateId\":\"WALLET-BILL@BLPaymentHelper\",\"title\":\"付款成功\",\"content\":\"{\\\"status\\\":\\\"付款成功\\\",\\\"date\\\":\\\"09月22日\\\",\\\"amountTip\\\":\\\"\\\",\\\"money\\\":\\\"15.00\\\",\\\"unit\\\":\\\"元\\\",\\\"infoTip\\\":\\\"\\\",\\\"failTip\\\":\\\"\\\",\\\"goto\\\":\\\"alipays://platformapi/startapp?appId\u003d20000003\u0026actionType\u003dtoBillDetails\u0026tradeNO\u003d2024092222001436291419263036\u0026bizType\u003dTRADE\\\",\\\"content\\\":[{\\\"title\\\":\\\"付款方式：\\\",\\\"content\\\":\\\"账户余额\\\"},{\\\"title\\\":\\\"交易对象：\\\",\\\"content\\\":\\\"膳当家黄焖鸡米饭（长沙中医药大学店）\\\"}],\\\"ad\\\":[],\\\"actions\\\":[{\\\"name\\\":\\\"\\\",\\\"url\\\":\\\"\\\"},{\\\"name\\\":\\\"查看详情\\\",\\\"url\\\":\\\"alipays://platformapi/startapp?appId\u003d20000003\u0026actionType\u003dtoBillDetails\u0026tradeNO\u003d2024092222001436291419263036\u0026bizType\u003dTRADE\\\"}]}\",\"linkName\":\"\",\"bizName\":\"支付助手\",\"msgCategory\":\"bill\",\"scm\":\"27.gotone.card.27f152a04e783f5e923911dcff538ce800629.MB_SEND_PH.null.payment_assist.10090.10099.2019062521000502094325.9991746\",\"assistInfo\":\"{\\\"showInFriendTab\\\":false,\\\"icon\\\":\\\"https://gw.alipayobjects.com/mdn/rms_f96971/afts/img/A*ZapXT6AjvG0AAAAAAAAAAABkARQnAQ\\\",\\\"reminderType\\\":\\\"point\\\",\\\"hiddenMsgHeader\\\":false,\\\"title\\\":\\\"支付助手\\\",\\\"reminderTypeModifyEnable\\\":false,\\\"assistId\\\":\\\"payment_assist\\\",\\\"desc\\\":\\\"支付宝资金变动通知\\\"}\",\"ih\":\"{\\\"extInfo\\\":{},\\\"iid\\\":\\\"105\\\",\\\"ioty\\\":\\\"aor\\\",\\\"itemBasicInfo\\\":{\\\"dn\\\":\\\"服务提醒\\\",\\\"ic\\\":\\\"https://gw.alipayobjects.com/zos/bmw-prod/b96c31e0-64ba-4cbb-9a64-73ff17d701fd.webp\\\",\\\"lk\\\":\\\"alipays://platformapi/startapp?appId\u003d20000235\u0026source\u003dfriendTab\\\"},\\\"itemUserRelation\\\":{\\\"ilf\\\":\\\"N\\\",\\\"uc\\\":{\\\"top\\\":\\\"0\\\"},\\\"version\\\":0},\\\"ity\\\":\\\"105\\\",\\\"moty\\\":\\\"u\\\",\\\"msgInfo\\\":{\\\"bm\\\":\\\"付款成功￥15.00 \\\",\\\"cmid\\\":\\\"27f152a04e783f5e923911dcff538ce800629\\\",\\\"lmt\\\":1727000023470,\\\"msrid\\\":\\\"00059_00094_zfzs001\\\",\\\"ncs\\\":\\\"N\\\",\\\"rps\\\":\\\"num\\\",\\\"sam\\\":\\\"Y\\\",\\\"ssrid\\\":\\\"PAY_HELPER_CARD_2088822946736298\\\",\\\"urn\\\":1}}\",\"bizMonitor\":\"{\\\"smid\\\":\\\"2088950089852440\\\",\\\"tinyAppId\\\":\\\"2021003124677450\\\",\\\"serviceCode\\\":\\\"MB_SEND_PH\\\",\\\"bizName\\\":\\\"\\\",\\\"createTime\\\":1727000023650,\\\"businessId\\\":\\\"PAY_HELPER_CARD_2088822946736298\\\",\\\"messageId\\\":\\\"27f152a04e783f5e923911dcff538ce800629\\\",\\\"messageTitle\\\":\\\"付款成功\\\",\\\"templateId\\\":\\\"WALLET-BILL@BLPaymentHelper\\\",\\\"tradeSource\\\":\\\"tinyApp\\\",\\\"status\\\":\\\"\\\"}\",\"languageType\":\"zh-Hans\",\"subscribeConfig\":\"0\",\"gmtCreate\":1727000023470,\"gmtValid\":2038040023459,\"operate\":\"SEND\",\"templateName\":\"支付助手\",\"homePageTitle\":\"付款成功￥15.00 \",\"status\":\"\",\"extraInfo\":\"{\\\"topSubContent\\\":\\\"付款成功\\\",\\\"preValue\\\":\\\"￥\\\",\\\"languageType\\\":\\\"zh-Hans\\\",\\\"isPaymentMsg\\\":true,\\\"assistName2\\\":\\\"交易对象\\\",\\\"assistName3\\\":\\\"\\\",\\\"assistName1\\\":\\\"付款方式\\\",\\\"templateId\\\":\\\"WALLET-FWC@remindNumber\\\",\\\"content\\\":\\\"15.00\\\",\\\"linkName\\\":\\\"\\\",\\\"assistMsg3\\\":\\\"\\\",\\\"sceneExt2\\\":{\\\"sceneUrl\\\":\\\"alipays://platformapi/startapp?appId\u003d20000003\u0026actionType\u003dtoBillDetails\u0026tradeNO\u003d2024092222001436291419263036\u0026bizType\u003dTRADE\\\",\\\"sceneType\\\":\\\"nativeApp\\\",\\\"sceneName\\\":\\\"膳当家黄焖鸡米饭（长沙中医药大学店）\\\",\\\"sceneIcon\\\":\\\"https://gw.alipayobjects.com/zos/mwalletmng/mukPPhtdXrnqECpCXXDq.png_[pixelWidth]x.png\\\"},\\\"assistMsg2\\\":\\\"膳当家黄焖鸡米饭（长沙中医药大学店）\\\",\\\"assistMsg1\\\":\\\"账户余额\\\",\\\"assistName4\\\":\\\"\\\",\\\"assistMsg5\\\":\\\"\\\",\\\"assistMsg4\\\":\\\"\\\",\\\"assistName5\\\":\\\"\\\",\\\"buttonLink\\\":\\\"\\\",\\\"cardAdInfo\\\":{\\\"p116\\\":{\\\"bizMonitor\\\":{\\\"marketingUniqueId\\\":\\\"MU5dc4999add7f49368e487536da2f19e4\\\",\\\"outBizId\\\":\\\"LIFE_MSG_TEXT|AMTT_drm|-\\\",\\\"marketingRuleId\\\":\\\"MR41b88eb9d64442b09a87a890d6848fc3\\\",\\\"style\\\":\\\"actionLine2\\\",\\\"marketingItemId\\\":\\\"MI501400035beb4580a6f92e161f06d081\\\"},\\\"expireTime\\\":1758536023615,\\\"marketingUniqueId\\\":\\\"MU5dc4999add7f49368e487536da2f19e4\\\",\\\"minClientVersion\\\":\\\"10.1.98\\\",\\\"recommendTemplateId\\\":\\\"actionLine2\\\",\\\"viewInfo\\\":{\\\"btnName\\\":\\\"支付奖励\\\",\\\"actionType\\\":\\\"link\\\",\\\"tagIcon\\\":\\\"https://mdn.alipayobjects.com/huamei_cke3ep/afts/img/A*s1xhTYe-_PQAAAAAAAAAAAAADk1-AQ/original\\\",\\\"tagColor\\\":\\\"#FF6011\\\",\\\"actionUrl\\\":\\\"alipays://platformapi/startapp?appId\u003d68687805\u0026url\u003dhttps%3A%2F%2Frender.alipay.com%2Fp%2Fyuyan%2F180020380000000023%2Fhome-page.html%3Fsource%3Ddzyyxiaoxi%26chInfo%3Ddzyyxiaoxi\\\",\\\"tag\\\":\\\"领2积分去兑红包\\\"}}}}\"}"}]
```

**Comment by Adlyq** [comment]
点击提示 未命中任何规则

**Comment by AnkioTomas** [comment]
> 点击提示 未命中任何规则

检查日志

**Comment by Adlyq** [comment]
```
2024-09-22 18:53:32  net.ankio.auto.xposed  [ERROR][HomeFragment.kt(322)]checkAppUpdate
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
  at com.google.gson.Gson.fromJson(Gson.java:1238)
  at com.google.gson.Gson.fromJson(Gson.java:1137)
  at com.google.gson.Gson.fromJson(Gson.java:1047)
  at com.google.gson.Gson.fromJson(Gson.java:982)
  at net.ankio.auto.update.AppUpdate.checkVersionFromGithub(AppUpdate.kt:58)
  at net.ankio.auto.update.AppUpdate$checkVersionFromGithub$1.invokeSuspend(null:14)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
  at android.os.Handler.handleCallback(Handler.java:958)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loopOnce(Looper.java:224)
  at android.os.Looper.loop(Looper.java:318)
  at android.app.ActivityThread.main(ActivityThread.java:8777)
  at java.lang.reflect.Method.invoke(Method.java:-2)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

2024-09-22 18:53:32  net.ankio.auto.xposed  [INFO][BaseUpdate.kt(136)]LocalVersion: v0.3.6,Version: v0.3.6
2024-09-22 18:53:31  net.ankio.auto.xposed  [WARN][AppDataAdapter.kt(93)]测试错误: 分类解析失败，可以先删除所有自定义分类后再试：Can't find bundle for base name org.mozilla.javascript.resources.Messages, locale zh_CN
2024-09-22 18:53:31  auto_server  [INFO][]规则识别结果: Can't find bundle for base name org.mozilla.javascript.resources.Messages, locale zh_CN
2024-09-22 18:53:31  auto_server  [ERROR][]Can't find bundle for base name org.mozilla.javascript.resources.Messages, locale zh_CN
2024-09-22 18:53:31  auto_server  [INFO][]规则识别结果: {"type":"Expend","money":15,"fee":0,"shopName":"膳当家黄焖鸡米饭（长沙中医药大学店）","shopItem":"付款成功￥15.00 ","accountNameFrom":"支付宝余额","accountNameTo":"","currency":"CNY","time":1727000024000,"channel":"支付宝[消费-支出]","ruleName":"支付宝消费"}

2024-09-22 18:53:31  auto_server  [INFO][]fromAppData: true
2024-09-22 18:53:30  net.ankio.auto.xposed  [WARN][AppDataAdapter.kt(93)]测试错误: 分类解析失败，可以先删除所有自定义分类后再试：Can't find bundle for base name org.mozilla.javascript.resources.Messages, locale zh_CN
2024-09-22 18:53:30  auto_server  [INFO][]规则识别结果: Can't find bundle for base name org.mozilla.javascript.resources.Messages, locale zh_CN
2024-09-22 18:53:30  auto_server  [ERROR][]Can't find bundle for base name org.mozilla.javascript.resources.Messages, locale zh_CN
2024-09-22 18:53:30  net.ankio.auto.xposed  [WARN][AppDataAdapter.kt(93)]测试错误: 未分析到有效账单。
2024-09-22 18:53:30  net.ankio.auto.xposed  [WARN][AppDataAdapter.kt(93)]测试错误: 未分析到有效账单。
2024-09-22 18:53:30  auto_server  [INFO][]规则识别结果: {"type":"Expend","money":15,"fee":0,"shopName":"膳当家黄焖鸡米饭（长沙中医药大学店）","shopItem":"付款成功￥15.00 ","accountNameFrom":"支付宝余额","accountNameTo":"","currency":"CNY","time":1727000024000,"channel":"支付宝[消费-支出]","ruleName":"支付宝消费"}

2024-09-22 18:53:30  auto_server  [INFO][]规则识别结果: 
2024-09-22 18:53:30  auto_server  [INFO][]规则识别结果: 
2024-09-22 18:53:30  auto_server  [INFO][]fromAppData: true
2024-09-22 18:53:30  auto_server  [INFO][]fromAppData: true
2024-09-22 18:53:30  auto_server  [INFO][]fromAppData: true
2024-09-22 18:53:29  net.ankio.auto.xposed  [ERROR][HomeFragment.kt(322)]checkAppUpdate
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
  at com.google.gson.Gson.fromJson(Gson.java:1238)
  at com.google.gson.Gson.fromJson(Gson.java:1137)
  at com.google.gson.Gson.fromJson(Gson.java:1047)
  at com.google.gson.Gson.fromJson(Gson.java:982)
  at net.ankio.auto.update.AppUpdate.checkVersionFromGithub(AppUpdate.kt:58)
  at net.ankio.auto.update.AppUpdate$checkVersionFromGithub$1.invokeSuspend(null:14)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
  at android.os.Handler.handleCallback(Handler.java:958)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loopOnce(Looper.java:224)
  at android.os.Looper.loop(Looper.java:318)
  at android.app.ActivityThread.main(ActivityThread.java:8777)
  at java.lang.reflect.Method.invoke(Method.java:-2)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

2024-09-22 18:53:29  net.ankio.auto.xposed  [INFO][BaseUpdate.kt(136)]LocalVersion: v0.3.6,Version: v0.3.6
```
